config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "people#index"
  resources :people do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は漢字・ひらがな・カタカナのいずれかで入力してください' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は漢字・ひらがな・カタカナのいずれかで入力してください' }
    validates :first_name_reading, format: { with: /\A[ァ-ヶー－]+\z/, message: 'はカタカナで入力してください' }
    validates :last_name_reading, format: { with: /\A[ァ-ヶー－]+\z/, message: 'はカタカナで入力してください' }
    validates :birthday
    validates :free_space
  end

  def self.search(search)
    Person.where(['first_name LIKE ? OR last_name LIKE ? OR first_name_reading LIKE ? OR last_name_reading LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は英字と数字を両方とも含んでください'

  with_options presence: true do
    validates :birthday
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は漢字・ひらがな・カタカナのいずれかで入力してください' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は漢字・ひらがな・カタカナのいずれかで入力してください' }
    validates :first_name_reading, format: { with: /\A[ァ-ヶー－]+\z/, message: 'はカタカナで入力してください' }
    validates :last_name_reading, format: { with: /\A[ァ-ヶー－]+\z/, message: 'はカタカナで入力してください' }
  end

  has_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_reading, :last_name_reading, :birthday])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @people = current_user.people
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    if params[:keyword] == ''
      redirect_to root_path
    else
      @people = Person.search(params[:keyword]).where(user_id: current_user.id)
    end
  end

  def show
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to person_path
    else
      render :edit
    end
  end

  def destroy
    if @person.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :first_name_reading, :last_name_reading, :hobby, :free_space, :email, :birthday).merge(user_id: current_user.id)
  end

  def set_item
    @person = Person.find(params[:id])
    redirect_to root_path unless current_user == @person.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonMemory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_person.html.erb
<li class='name-li'>
  <%= link_to person_path(person.id), class:'link' do %>
    <%= person.first_name %>
    <%= person.last_name %>
    <span class='name-read-li'>
      <%= person.first_name_reading %>
      <%= person.last_name_reading %>
    </span>
  <% end %>
</li>

app/views/people/edit.html.erb
<%= render "shared/header" %>

<div class="memory-main">
  <div class="memory-title">人の情報を入力</div>
  <%= form_with model: @person, local: true do |f| %>

  <%= render 'shared/error_messages', model: @person %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 記憶" %>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name_reading, class:"input-name", id:"first-name-kana", placeholder:"例) キオク" %>
      <%= f.text_area :last_name_reading, class:"input-name", id:"last-name-kana", placeholder:"例) タロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 1),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">趣味</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :hobby, class:"input-hobby", id:"first-name", placeholder:"例) ゴルフ" %>
    </div>
  </div>
  <div class="items-explain">
    <div class="form-text">
      フリースペース
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :free_space, class:"items-text", id:"item-info", placeholder:"フリースペース（200文字まで）" ,rows:"5" ,maxlength:"200" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">Email</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :email, class:"input-hobby", id:"first-name", placeholder:"例) memory@memory" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "変更する" ,class:"memory-btn" %>
    <%=link_to 'もどる', person_path(@person.id), class:"back-btn" %>
  </div>
  <% end %>
</div>

<%= render "shared/footer"%>

app/views/people/index.html.erb
<%= render "shared/header" %>
<div class='top-page-main'>
  <div class='top-page-title'>
    Person 一覧
  </div>
  <%= form_with url: search_people_path, local: true, method: :get, class:'search-box' do |form| %>
    <%= form.text_field :keyword, placeholder: "名前を検索する", class: "search-word" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <ul class='person-lists'>
    <% if @people.present? %>
      <%= render partial: 'person', collection: @people %>
    <% end %>
  </ul>
</div>

<%= render "shared/footer"%>

<%= link_to new_person_path do%>
  <div class='memories-btn'>
    <div class='memories-btn-text'>記録する</div>
  </div>
<% end %>

app/views/people/new.html.erb
<%= render "shared/header" %>

<div class="memory-main">
  <div class="memory-title">人の情報を入力</div>
  <%= form_with model: @person, local: true do |f| %>

  <%= render 'shared/error_messages', model: @person %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 記憶" %>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name_reading, class:"input-name", id:"first-name-kana", placeholder:"例) キオク" %>
      <%= f.text_area :last_name_reading, class:"input-name", id:"last-name-kana", placeholder:"例) タロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 1),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">趣味</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :hobby, class:"input-hobby", id:"first-name", placeholder:"例) ゴルフ" %>
    </div>
  </div>
  <div class="items-explain">
    <div class="form-text">
      フリースペース
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :free_space, class:"items-text", id:"item-info", placeholder:"フリースペース（200文字まで）" ,rows:"5" ,maxlength:"200" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">Email</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :email, class:"input-hobby", id:"first-name", placeholder:"例) memory@memory" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "記録する" ,class:"memory-btn" %>
    <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>
  <% end %>
</div>

<%= render "shared/footer"%>

app/views/people/search.html.erb
<%= render "shared/header" %>
<div class='top-page-main'>
  <div class='top-page-title'>
    Person 検索結果一覧
  </div>
  <%= form_with url: search_people_path, local: true, method: :get, class:'search-box' do |form| %>
    <%= form.text_field :keyword, placeholder: "名前を検索する", class: "search-word" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <ul class='person-lists'>
    <% if @people.present? %>
      <%= render partial: 'person', collection: @people %>
    <% end %>
  </ul>
  <div class="sign-up-pages">
    <%= link_to "一覧表示に戻る", root_path, class:"sign-up-page"%>
  </div>
</div>

<%= render "shared/footer"%>

<%= link_to new_person_path do%>
  <div class='memories-btn'>
    <div class='memories-btn-text'>記録する</div>
  </div>
<% end %>

app/views/people/show.html.erb
<%= render "shared/header" %>

<div class='item-show'>
  <div class="item-box">
    <div class='show-page-title'>
      <%= @person.first_name%>  <%= @person.last_name %>
    </div>
    <div class="detail-item">＜年齢＞
      <div class="detail-value">
        <%= (Date.today.strftime('%Y%m%d').to_i - @person.birthday.strftime('%Y%m%d').to_i) / 10000 %>
      </div>
    </div>
    <div class="detail-item">＜誕生日＞
      <div class="detail-value"><%= @person.birthday.strftime('%Y年%m月%d日') %></div>
    </div>
    <% if @person.hobby.present? %>
      <div class="detail-item">＜趣味＞
        <div class="detail-value"><%= @person.hobby %></div>
      </div>
    <% end %>
    <div class="detail-item">＜その他の情報＞
      <div class="detail-value"><%= @person.free_space %></div>
    </div>
    <% if @person.email.present? %>
      <div class="detail-item">＜Eメール＞
        <div class="detail-value"><%= @person.email %></div>
      </div>
    <% end %>
    <%= link_to '情報の編集', edit_person_path(@person.id), method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', person_path(@person.id), method: :delete, class:'item-destroy' %>
    <div class="sign-up-pages">
      <%= link_to "一覧表示に戻る", root_path, class:"sign-up-page"%>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

<%= link_to new_person_path do%>
  <div class='memories-btn'>
    <div class='memories-btn-text'>記録する</div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
</div>

app/views/shared/_footer_second.html.erb
<div class='footer-second'>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to 'Person Memory', "/", class:"food-selection" %>
    <div class='nav'>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
    </div>
  </div>
</header>

app/views/shared/_header_second.html.erb
<div class="header-second">
  <div class='second-name'>Person Memory</div>
</div>